In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [ ]:
df=pd.read_csv('IMDB Dataset.csv')

In [ ]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
# One review
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

**Text Cleaning**

1. Remove html tags
2. Remove Special Characters
3. Converting every thing to lower case
4. Removing Stop Words
5. Stemming

In [ ]:
df=df.sample(10000)
df.shape

(10000, 2)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10000 entries, 5406 to 30760
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     10000 non-null  object
 1   sentiment  10000 non-null  object
dtypes: object(2)
memory usage: 234.4+ KB


In [ ]:
df['sentiment'].replace({'positive':1, 'negative':0},inplace=True)

In [ ]:
df.head()

review  sentiment
5406   i went to see this movie with a bunch of frien...          1
37376  I saw "Myra Breckinridge" when it first came o...          0
13698  I was looking forward to seeing Amanda Peet in...          0
31357  (No spoilers, just plot details) I can't under...          1
26440  DeCoteau has to be one of the worst "directors...          0

In [ ]:
# Regular Expression Library to removes html tag= get this code from net
import re
clean=re.compile('<.*?>')
re.sub(clean,'',df.iloc[2].review)

'I was looking forward to seeing Amanda Peet in another good role after recently renting "The Whole Nine Yards"--easily worth the rental, by the way--but this wasn\'t it.I remembered that the trailer for "Whipped" was somewhat funny and the plot about three oversexed New Yorker twenty somethings all falling for and getting manipulated by the charming Ms. Peet was worth a shot. So, I convinced two friends one afternoon to come see this movie with me. This review is my penance.In the first act we have the three lead studs, recounting their conquests in a diner. What should have been funny, or at least telling, comes out rather pathetic. Was there any redeeming quality about the three men and their encounters that we were supposed to get out of this?[And while I don\'t mind movies that are cheerfully vulgar, I kept wondering why no one in the diner turned around when the studs talk loudly about sexual and scatalogical details. They do this every week at the same diner? You would think som

In [ ]:
# Function to clean html tags
def clean_html(text):
    clean=re.compile('<.*?>')
    return re.sub(clean, '', text)

In [ ]:
df['review']=df['review'].apply(clean_html)

In [ ]:
# converting everythimg to lower
def convert_lower(text):
    return text.lower()

In [ ]:
df['review']=df['review'].apply(convert_lower)

In [ ]:
# function to remove special characters

def remove_special(text):
    x=''
    for i in text:
        if i.isalnum():
            x=x+i
        else:
            x=x+' '
    return x

In [ ]:
remove_special('Th%e @ classic use of the word. it is called oz as that is the nickname given to the oswald maximum security state')

'Th e   classic use of the word  it is called oz as that is the nickname given to the oswald maximum security state'

In [ ]:
df['review']=df['review'].apply(remove_special)

In [ ]:
# Remove the stop words
 
import nltk

In [ ]:
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [ ]:
df

review  sentiment
5406   i went to see this movie with a bunch of frien...          1
37376  i saw  myra breckinridge  when it first came o...          0
13698  i was looking forward to seeing amanda peet in...          0
31357   no spoilers  just plot details  i can t under...          1
26440  decoteau has to be one of the worst  directors...          0
...                                                  ...        ...
20701  it seems that the people behind envy realised ...          0
19632  this movie has two new features in relation to...          1
26542  it is really a shame that imdb doesn t let you...          0
27015  what does this movie have  lots of gunfire and...          0
30760  a small town schoolteacher  geena davis  slowl...          1

[10000 rows x 2 columns]

In [ ]:
def remove_stopwords(text):
    x=[]
    for i in text.split():
        
        if i not in stopwords.words('english'):
            x.append(i)
    y=x[:]
    x.clear()
    return y

In [ ]:
df['review']=df['review'].apply(remove_stopwords)

In [ ]:
df

review  sentiment
5406   [went, see, movie, bunch, friends, one, night,...          1
37376  [saw, myra, breckinridge, first, came, 1970, h...          0
13698  [looking, forward, seeing, amanda, peet, anoth...          0
31357  [spoilers, plot, details, understand, hatred, ...          1
26440  [decoteau, one, worst, directors, working, tod...          0
...                                                  ...        ...
20701  [seems, people, behind, envy, realised, recent...          0
19632  [movie, two, new, features, relation, message,...          1
26542  [really, shame, imdb, let, give, negative, vot...          0
27015  [movie, lots, gunfire, expensive, effects, not...          0
30760  [small, town, schoolteacher, geena, davis, slo...          1

[10000 rows x 2 columns]

In [ ]:
# Perform stemming

from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [ ]:
y=[]
def stem_words(text):
    for i in text:
        y.append(ps.stem(i))
    z=y[:]
    y.clear()
    return z

In [ ]:
stem_words(['I','loved','loving','it'])

['i', 'love', 'love', 'it']

In [ ]:
df['review']=df['review'].apply(stem_words)

In [ ]:
df

review  sentiment
5406   [went, see, movi, bunch, friend, one, night, r...          1
37376  [saw, myra, breckinridg, first, came, 1970, he...          0
13698  [look, forward, see, amanda, peet, anoth, good...          0
31357  [spoiler, plot, detail, understand, hatr, epis...          1
26440  [decoteau, one, worst, director, work, today, ...          0
...                                                  ...        ...
20701  [seem, peopl, behind, envi, realis, recent, co...          0
19632  [movi, two, new, featur, relat, messag, convey...          1
26542  [realli, shame, imdb, let, give, neg, vote, hi...          0
27015  [movi, lot, gunfir, expens, effect, noth, make...          0
30760  [small, town, schoolteach, geena, davi, slowli...          1

[10000 rows x 2 columns]

In [ ]:
# Join back

def join_back(list_input):
    return " ".join(list_input)

In [ ]:
df['review']=df['review'].apply(join_back)

In [ ]:
df['review']

5406     went see movi bunch friend one night realli he...
37376    saw myra breckinridg first came 1970 healthi 2...
13698    look forward see amanda peet anoth good role r...
31357    spoiler plot detail understand hatr episod wan...
26440    decoteau one worst director work today genr no...
                               ...                        
20701    seem peopl behind envi realis recent comedi es...
19632    movi two new featur relat messag convey equal ...
26542    realli shame imdb let give neg vote hideous aw...
27015    movi lot gunfir expens effect noth make sens l...
30760    small town schoolteach geena davi slowli begin...
Name: review, Length: 10000, dtype: object

In [ ]:
X=df.iloc[:,0:1].values

In [ ]:
X.shape

(10000, 1)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=1000)

In [ ]:
X=cv.fit_transform(df['review']).toarray()

In [ ]:
X.shape

(10000, 1000)

In [ ]:
y=df.iloc[:,-1].values

In [ ]:
X[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,

In [ ]:
X[0].max()

4

In [ ]:
X[0].mean()

0.053

In [ ]:
y=df.iloc[:,-1].values

In [ ]:
y.shape

(10000,)

In [ ]:
# spilt data into two parts
# X,Y
# Training set
# Test set ( already know the result)

In [ ]:
from  sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.2)

In [ ]:
X_train.shape

(8000, 1000)

In [ ]:
X_test.shape

(2000, 1000)

In [ ]:
y_train.shape

(8000,)

In [ ]:
y_test.shape

(2000,)

In [ ]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB

In [ ]:
clf1=GaussianNB()
clf2=MultinomialNB()
clf3=BernoulliNB()

In [ ]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)
clf3.fit(X_train,y_train)

BernoulliNB()

In [ ]:
y_pred1=clf1.predict(X_test)
y_pred2=clf2.predict(X_test)
y_pred3=clf3.predict(X_test)

In [ ]:
y_test.shape

(2000,)

In [ ]:
y_pred1.shape

(2000,)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
from scipy.stats import mode

def majority_vote_predictions(y_test_lists):
  y_test_np = np.array(y_test_lists)
  print(y_test_np)
  return mode(y_test_np, axis=0)[0][0]

In [ ]:
predictions_ens = majority_vote_predictions([y_pred1, y_pred2, y_pred3])

[[1 1 0 ... 1 1 0]
 [1 1 0 ... 1 1 1]
 [1 1 1 ... 1 1 1]]


In [ ]:
predictions_ens 

array([1, 1, 0, ..., 1, 1, 1])

In [ ]:
print("Gausssian ", accuracy_score(y_test,y_pred1))
print("Multinomial ", accuracy_score(y_test,y_pred2))
print("Bernaulli ", accuracy_score(y_test,y_pred3))
print("MV Ensemble of the 3: ", accuracy_score(y_test, predictions_ens))

Gausssian  0.764
Multinomial  0.838
Bernaulli  0.8445
MV Ensemble of the 3:  0.835
